# pylint: disable=line-too-long,invalid-name
import copy
import enum
import json
import os
import pathlib
import textwrap
import urllib.parse
from pathlib import Path
from typing import Any, Dict, Generator, List, Union

import yaml
from dagster import (
    AssetExecutionContext,
    AssetIn,
    AssetKey,
    AssetMaterialization,
    AssetsDefinition,
    MetadataValue,
    Output,
    asset,
)
from OpenStudioLandscapes.engine.common_assets import (
    cmd,
    compose,
    docker_compose_graph,
    feature,
    feature_out,
    group_in,
    group_out,
)
from OpenStudioLandscapes.engine.config.models import ConfigEngine, DockerConfigModel
from OpenStudioLandscapes.engine.constants import (
    ASSET_HEADER_BASE,
    ConfigParent,
)
from OpenStudioLandscapes.engine.enums import (
    DockerComposePolicies,
)
from OpenStudioLandscapes.engine.link.models import OpenStudioLandscapesFeatureIn
from OpenStudioLandscapes.engine.utils import (
    create_image,
    download_file,
    get_apt_install_str,
    get_docker_compose_names,
    get_docker_run_cmd,
    get_image_metadata,
    get_relative_path_via_common_root,
)
from OpenStudioLandscapes.engine.utils.docker.compose_dicts import (
    get_network_dicts,
)

from OpenStudioLandscapes.Grafana import (
    config,
    dist,
    ASSET_HEADER,
)

# https://github.com/yaml/pyyaml/issues/722#issuecomment-1969292770
yaml.SafeDumper.add_multi_representer(
    data_type=enum.Enum,
    representer=yaml.representer.SafeRepresenter.represent_str,
)

cmd: AssetsDefinition = cmd.get_feature__cmd(
    ASSET_HEADER=ASSET_HEADER,
)

CONFIG: AssetsDefinition = feature.get_feature__CONFIG(
    ASSET_HEADER=ASSET_HEADER,
    CONFIG_STR=config.models.CONFIG_STR,
    search_model_of_type=config.models.Config,
)

feature_in: AssetsDefinition = group_in.get_feature_in(
    ASSET_HEADER=ASSET_HEADER,
    ASSET_HEADER_BASE=ASSET_HEADER_BASE,
    ASSET_HEADER_FEATURE_IN={},
)

group_out: AssetsDefinition = group_out.get_group_out(
    ASSET_HEADER=ASSET_HEADER,
)

docker_compose_graph: AssetsDefinition = docker_compose_graph.get_docker_compose_graph(
    ASSET_HEADER=ASSET_HEADER,
)

compose: AssetsDefinition = compose.get_compose(
    ASSET_HEADER=ASSET_HEADER,
)

feature_out_v2: AssetsDefinition = feature_out.get_feature_out_v2(
    ASSET_HEADER=ASSET_HEADER,
)

# Produces
# - feature_in_parent
# - CONFIG_PARENT
# if ConfigParent is or type FeatureBaseModel
feature_in_parent: Union[AssetsDefinition, None] = group_in.get_feature_in_parent(
    ASSET_HEADER=ASSET_HEADER,
    config_parent=ConfigParent,
)


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description=textwrap.dedent("""
        - https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
        """),
)
def grafana_ini(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    env: Dict = CONFIG.env

    # @formatter:off
    grafana_ini = textwrap.dedent("""\
        # {auto_generated}
        # {dagster_url}
        # Full documentation
        # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
        # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
        # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
        [security]
        admin_user = {grafana_admin_user}
        admin_password = {grafana_password}
        
        [server]
        root_url = {grafana_root_url}
        """).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        grafana_admin_user=CONFIG.grafana_admin_user,
        grafana_password=CONFIG.grafana_admin_password,
        grafana_root_url=CONFIG.grafana_root_url,
        **env,
    )
    # @formatter:on

    grafana_ini_path = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "etc",
        "grafana",
        "grafana.ini",
    ).expanduser()

    grafana_ini_path.parent.mkdir(parents=True, exist_ok=True)

    with open(grafana_ini_path, "w") as fw:
        fw.write(grafana_ini)

    yield Output(grafana_ini_path)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(grafana_ini_path),
            "grafana_ini": MetadataValue.md(f"```\n{grafana_ini}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description=textwrap.dedent("""
        A good start to understand how Alloy works:
        - [Christian Lempa](https://www.youtube.com/watch?v=E654LPrkCjo)
        
        - [Configuration Blocks](https://grafana.com/docs/alloy/latest/reference/config-blocks/)
        - [Alloy Components](https://grafana.com/docs/alloy/latest/reference/components/)
        """),
)
def alloy_config(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:

    env: Dict = CONFIG.env

    alloy_config_path = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "alloy",
        "alloy.config",
    ).expanduser()

    alloy_config_path.parent.mkdir(parents=True, exist_ok=True)

    with open(alloy_config_path, "w") as fw:
        fw.write(CONFIG.alloy_config)

    yield Output(alloy_config_path)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(alloy_config_path),
            "alloy_config": MetadataValue.md(f"```\n{CONFIG.alloy_config}\n```"),
            "alloy_config_template": MetadataValue.md(
                f"```\n{CONFIG.alloy_config_template}\n```"
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description=textwrap.dedent("""
        Verify that Loki is up and running.

        - To view readiness, navigate to http://localhost:3100/ready.
        - To view metrics, navigate to http://localhost:3100/metrics.
        
        Official Resources:
        - https://grafana.com/docs/loki/latest/configure/
        """),
)
def loki_yaml(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    env: Dict = CONFIG.env

    loki_dict = {
        "auth_enabled": False,
        "server": {
            "http_listen_port": CONFIG.grafana_loki_port_container,
            # "grpc_listen_port": 9096,
            # "log_level": CONFIG.grafana_loki_loglevel.value,
            # "grpc_server_max_concurrent_streams": 1000,
        },
        "common": {
            "instance_addr": "0.0.0.0",
            "path_prefix": "/tmp/loki",
            "storage": {
                "filesystem": {
                    "chunks_directory": "/tmp/loki/chunks",
                    "rules_directory": "/tmp/loki/rules",
                },
            },
            "replication_factor": 1,
            "ring": {
                "kvstore": {
                    "store": "inmemory",
                },
            },
        },
        "query_range": {
            "results_cache": {
                "cache": {
                    "embedded_cache": {
                        "enabled": True,
                        "max_size_mb": 100,
                    },
                },
            },
        },
        "limits_config": {
            "metric_aggregation_enabled": True,
            "volume_enabled": True,
        },
        "schema_config": {
            "configs": [
                {
                    "from": "2020-10-24",
                    "store": "tsdb",
                    "object_store": "filesystem",
                    "schema": "v13",
                    "index": {"prefix": "index_", "period": "24h"},
                }
            ],
        },
        "storage_config": {
            "tsdb_shipper": {
                "active_index_directory": "/tmp/loki/index",
                "cache_location": "/tmp/loki/index_cache",
            },
            "filesystem": {
                "directory": "/tmp/loki/chunks",
            },
        },
        "pattern_ingester": {
            "enabled": True,
            # "metric_aggregation": {
            #     "loki_address": "localhost:3100",
            # },
        },
        # "ruler": {
        #     "alertmanager_url": "http://localhost:9093",
        # },
        # "frontend": {
        #     "encoding": "protobuf",
        # },
        "analytics": {
            "reporting_enabled": False,
        },
    }

    loki_dict_yaml = yaml.dump(loki_dict)

    loki_yaml_path = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "loki",
        "loki.yaml",
    ).expanduser()

    loki_yaml_path.parent.mkdir(parents=True, exist_ok=True)

    with open(loki_yaml_path, "w") as fw:
        fw.write(loki_dict_yaml)

    yield Output(loki_yaml_path)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(loki_yaml_path),
            "loki_yaml": MetadataValue.md(f"```yaml\n{loki_dict_yaml}\n```"),
        },
    )


# Todo
#  - [x] Create Alloy image with `zfsutils-linux`
#        - References:
#          - https://github.com/michimussato/OpenStudioLandscapes-Kitsu/blob/b794644e86e37153b17378a0e234c620332ed03e/src/OpenStudioLandscapes/Kitsu/assets.py#L211


@asset(
    **ASSET_HEADER,
    ins={
        "feature_in": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "feature_in"]),
        ),
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
)
def write_dockerfile_alloy(
    context: AssetExecutionContext,
    feature_in: OpenStudioLandscapesFeatureIn,  # pylint: disable=redefined-outer-name
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    docker_config: DockerConfigModel = config_engine.openstudiolandscapes__docker_config

    docker_image: Dict = feature_in.openstudiolandscapes_base.docker_image_base

    docker_file = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "__".join(context.asset_key.path),
        "Dockerfiles",
        "Dockerfile",
    )

    docker_file.parent.mkdir(parents=True, exist_ok=True)

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        env=env,
    )

    #################################################

    apt_install_str_base: str = get_apt_install_str(
        apt_install_packages=CONFIG.alloy_apt_packages,
    )

    # @formatter:off
    docker_file_str = textwrap.dedent("""\
        # {auto_generated}
        # {dagster_url}
        # https://hub.docker.com/r/grafana/alloy
        FROM {parent_image} AS {image_name}
        LABEL authors="{AUTHOR}"

        {apt_install_str_base}

        # WORKDIR /opt/zou

        # ENTRYPOINT []
        """).format(
        apt_install_str_base=apt_install_str_base,
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        image_name=image_name,
        parent_image=CONFIG.alloy_image,
        **env,
    )
    # @formatter:on

    with open(docker_file, "w") as fw:
        fw.write(docker_file_str)

    with open(docker_file, "r") as fr:
        docker_file_content = fr.read()

    yield Output(docker_file)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(docker_file),
            docker_file.name: MetadataValue.md(f"```shell\n{docker_file_content}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "feature_in": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "feature_in"]),
        ),
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "write_dockerfile_alloy": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "write_dockerfile_alloy"])
        ),
    },
)
def build_docker_image_alloy(
    context: AssetExecutionContext,
    feature_in: OpenStudioLandscapesFeatureIn,  # pylint: disable=redefined-outer-name
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    write_dockerfile_alloy: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
    """ """

    # Todo:
    #  - [ ] OpenStudioLandsc…er_image_alloy
    #        INFO
    #        stderr: #5 39.43 /var/lib/dpkg/info/zfsutils-linux.postinst: 25: modprobe: not found
    #  - [ ] ZFS support is not needed anymore (storage is back to ext4)

    env: Dict = CONFIG.env

    docker_config_json: pathlib.Path = (
        feature_in.openstudiolandscapes_base.docker_config_json
    )

    config_engine: ConfigEngine = CONFIG.config_engine

    docker_config: DockerConfigModel = config_engine.openstudiolandscapes__docker_config

    docker_image: Dict = feature_in.openstudiolandscapes_base.docker_image_base

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        env=env,
    )

    #################################################

    image_data, logs = create_image(
        context=context,
        image_name=image_name,
        image_prefixes=image_prefixes,
        tags=tags,
        docker_image=docker_image,
        docker_config=docker_config,
        docker_config_json=docker_config_json,
        docker_file=write_dockerfile_alloy,
    )

    yield Output(image_data)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(image_data),
            "env": MetadataValue.json(env),
            "docker_image": MetadataValue.path(
                f"{image_data['image_prefixes']}{image_data['image_name']}:{image_data['image_tags'][0]}"
            ),
            "docker_cmd": MetadataValue.path(
                get_docker_run_cmd(
                    context=context,
                    image_data=image_data,
                )
            ),
            "logs": MetadataValue.json(logs),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description=textwrap.dedent("""
        Verify that Loki is up and running.

        Official Resources:
        - https://prometheus.io/docs/prometheus/latest/configuration/configuration/
        
        File Based Service-Discovery:
        - https://www.compilenrun.com/docs/observability/prometheus/prometheus-fundamentals/prometheus-configuration/#using-file-based-service-discovery
        """),
)
def prometheus_yaml(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    env: Dict = CONFIG.env

    # Prometheus
    # enable remote write
    # - https://grafana.com/docs/alloy/latest/tutorials/send-metrics-to-prometheus/#third-component-write-metrics-to-prometheus

    # https://prometheus.io/docs/prometheus/latest/command-line/prometheus/#flags
    prometheus_dict = {
        "global": {
            # Set the scrape interval to every 15 seconds. Default is every 1 minute.
            "scrape_interval": "15s",
            # Evaluate rules every 15 seconds. The default is every 1 minute.
            "evaluation_interval": "15s",
        },
        # Grafana raises Errors with these settings
        # "storage": {
        #     "tsdb": {
        #         "path": "data/",
        #         "retention": {
        #             "time": "1w",
        #             "size": "1GB"
        #         },
        #     },
        # },
        # Alertmanager configuration
        # "alerting": {
        #     "alertmanagers": [],
        # },
        "scrape_configs": [
            # {
            #     "job_name": "prometheus",
            #     "static_configs": [
            #         {
            #             "targets": [
            #                 # f"prometheus:{CONFIG.prometheus_port_container}",
            #                 f"localhost:{CONFIG.prometheus_port_host}",
            #             ],
            #         }
            #     ],
            # },
            {
                # ready made for
                # https://prometheus.io/docs/guides/node-exporter/
                # https://github.com/prometheus/node_exporter?tab=readme-ov-file
                # https://grafana.com/grafana/dashboards/1860-node-exporter-full/
                # - requires job_name = "node"
                # ‘–collector.systemd –collector.processes’
                "job_name": "node",
                "static_configs": [
                    {
                        # Todo
                        #  - [ ] File-based service discovery for dynamic targets.
                        "targets": [
                            # prometheus because
                            # 9100 is node exporter default port
                            "localhost:9100",
                        ]
                    },
                ],
            },
        ],
    }

    prometheus_dict_yaml = yaml.dump(prometheus_dict)

    prometheus_yaml_path = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "prometheus",
        "prometheus.yaml",
    ).expanduser()

    prometheus_yaml_path.parent.mkdir(parents=True, exist_ok=True)

    with open(prometheus_yaml_path, "w") as fw:
        fw.write(prometheus_dict_yaml)

    yield Output(prometheus_yaml_path)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(prometheus_yaml_path),
            "prometheus_yaml": MetadataValue.md(
                f"```yaml\n{prometheus_dict_yaml}\n```"
            ),
        },
    )


# @asset(
#     **ASSET_HEADER,
#     ins={
#         "CONFIG": AssetIn(
#             AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
#         ),
#     },
#     description=textwrap.dedent(
#         """
#         """
#     )
# )
# def mimir_yaml(
#         context: AssetExecutionContext,
#         CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
# ) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
#     env: Dict = CONFIG.env
#
#     # https://grafana.com/docs/mimir/latest/get-started/#start-grafana-mimir
#     mimir_dict = {
#         "multitenancy_enabled": False,
#         "blocks_storage": {
#             "backend": "filesystem",
#             "bucket_store": {
#                 "sync_dir": "/tmp/mimir/tsdb-sync",
#             },
#             "filesystem": {
#                 "dir": "/tmp/mimir/data/tsdb",
#             },
#             "tsdb": {
#                 "dir": "/tmp/mimir/tsdb",
#             },
#         },
#         "compactor": {
#             "data_dir": "/tmp/mimir/compactor",
#             "sharding_ring": {
#                 "kvstore": {
#                     "store": "memberlist",
#                 },
#             },
#         },
#         "distributor": {
#             "ring": {
#                 "instance_addr": "127.0.0.1",
#                 "kvstore": {
#                     "store": "memberlist",
#                 },
#             },
#         },
#         "ingester": {
#             "ring": {
#                 "instance_addr": "127.0.0.1",
#                 "kvstore": {
#                     "store": "memberlist",
#                 },
#                 "replication_factor": 1,
#             },
#         },
#         "ruler_storage": {
#             "backend": "filesystem",
#             "filesystem": {
#                 "dir": "/tmp/mimir/rules",
#             },
#         },
#         "server": {
#             "http_listen_port": CONFIG.grafana_mimir_port_container,
#             "log_level": "debug",
#         },
#         "store_gateway": {
#             "sharding_ring": {
#                 "replication_factor": 1,
#             },
#         },
#     }
#
#     mimir_dict_yaml = yaml.dump(mimir_dict)
#
#     mimir_yaml_path = pathlib.Path(
#         env["DOT_LANDSCAPES"],
#         env.get("LANDSCAPE", "default"),
#         f"{dist.name}",
#         "mimir",
#         "config.yaml",
#     ).expanduser()
#
#     mimir_yaml_path.parent.mkdir(parents=True, exist_ok=True)
#
#     with open(mimir_yaml_path, "w") as fw:
#         fw.write(mimir_dict_yaml)
#
#     yield Output(mimir_yaml_path)
#
#     yield AssetMaterialization(
#         asset_key=context.asset_key,
#         metadata={
#             "__".join(context.asset_key.path): MetadataValue.path(mimir_yaml_path),
#             "mimir_dict_yaml": MetadataValue.md(f"```yaml\n{mimir_dict_yaml}\n```"),
#         },
#     )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description=textwrap.dedent("""
        - [](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources)
        - [](https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-data-source)
        """),
)
def data_sources_grafana(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    env: Dict = CONFIG.env

    # config_engine: ConfigEngine = CONFIG.config_engine

    service_name_loki = "loki"
    service_name_prometheus = "prometheus"
    # container_name_loki, host_name_loki = get_docker_compose_names(
    #     context=context,
    #     service_name=service_name_loki,
    #     landscape_id=env.get("LANDSCAPE", "default"),
    #     domain_lan=config_engine.openstudiolandscapes__domain_lan,
    # )

    datasources_loki_dict = {
        "apiVersion": 1,
        "datasources": [
            # Loki
            {
                "name": "Loki",
                "type": "loki",
                "access": "proxy",
                "orgId": 1,
                "url": f"http://{service_name_loki}:{CONFIG.grafana_loki_port_container}",
                "basicAuth": False,
                "isDefault": True,
                "version": 1,
                "editable": False,
                # "jsonData": {
                #     "timeout": 60,
                #     "maxLines": 1000,
                # },
            },
            # Prometheus
            {
                "name": "Prometheus",
                "type": "prometheus",
                "access": "proxy",
                "orgId": 1,
                "url": f"http://{service_name_prometheus}:{CONFIG.prometheus_port_container}",
                "basicAuth": False,
                "isDefault": False,
                "version": 1,
                "editable": False,
                # "jsonData": {
                #     "timeout": 60,
                #     "maxLines": 1000,
                # },
            },
            # Todo: maybe someday
            # Mimir
            # {
            #     "name": "Loki",
            #     "type": "loki",
            #     "access": "proxy",
            #     "orgId": 1,
            #     "url": f"http://{service_name_loki}:{CONFIG.grafana_loki_port_container}",
            #     "basicAuth": False,
            #     "isDefault": True,
            #     "version": 1,
            #     "editable": False,
            #     "jsonData": {
            #         "timeout": 60,
            #         "maxLines": 1000,
            #     },
            # },
        ],
    }

    datasources_grafana_dict_yaml = yaml.dump(datasources_loki_dict)

    loki_yaml_path = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "datasources",
        "datasources.yaml",
    ).expanduser()

    loki_yaml_path.parent.mkdir(parents=True, exist_ok=True)

    with open(loki_yaml_path, "w") as fw:
        fw.write(datasources_grafana_dict_yaml)

    yield Output(loki_yaml_path)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(loki_yaml_path),
            "datasources_grafana_dict_yaml": MetadataValue.md(
                f"```yaml\n{datasources_grafana_dict_yaml}\n```"
            ),
        },
    )


# Todo
@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description=textwrap.dedent("""
        - [](https://grafana.com/tutorials/provision-dashboards-and-data-sources/)
        """),
)
def dashboards_grafana(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[
    Output[
        dict[
            str,
            Path
            | dict[
                str, int | list[dict[str, str | bool | int | dict[str, str | bool]]]
            ],
        ]
    ]
    | AssetMaterialization
    | Any,
    None,
    None,
]:
    env: Dict = CONFIG.env

    # config_engine: ConfigEngine = CONFIG.config_engine

    # dashboards = {
    #     "Node Exporter Full": {
    #         "url": "https://grafana.com/api/dashboards/1860/revisions/42/download",
    #         "id": 1860,
    #         "outfile": None,
    #     },
    #     "cAdvisor Docker Insights": {
    #         "url": "https://grafana.com/api/dashboards/19908/revisions/1/download",
    #         "id": 19908,
    #         "outfile": None,
    #     },
    # }

    dashboards_repo = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "dashboards_repo",
    ).expanduser()

    dashboards_repo.mkdir(parents=True, exist_ok=True)

    dashboards = copy.deepcopy(CONFIG.grafana_dashboards)

    for dashboard, value in dashboards.items():
        # results in "download", hence: rename file after download
        file_path = download_file(
            url=value["url"],
            dest_folder=dashboards_repo,
        )
        file_path.rename(file_path.parent / f"{value['id']}.json")
        value["outfile"] = file_path
        # with open(file_path, "r") as fr:
        #     dashboard_dict = json.load(fr)
        #
        # if "__inputs" in dashboard_dict:
        #     if not bool(dashboard_dict["__inputs"]):
        #         dashboard_dict["__inputs"] = {}

    """
    After add Variable DS_PROMETHEUS to 19908,
    the diff looks like this:
      "templating": {
        - "list": []
        + "list": [
        +   {
        +     "current": {
        +       "text": "Prometheus",
        +       "value": "PBFA97CFB590B2093"
        +     },
        +     "description": "",
        +     "label": "Datasource",
        +     "name": "DS_PROMETHEUS",
        +     "options": [],
        +     "query": "prometheus",
        +     "refresh": 1,
        +     "regex": "",
        +     "type": "datasource"
        +   }
        + ]
      },
    """

    dashboards_dict = {
        "apiVersion": 1,
        "providers": [
            {
                "name": "Dashboard Provider",
                "type": "file",
                "disableDeletion": True,
                "orgId": 1,
                "allowUiUpdates": True,
                "options": {
                    "path": "/etc/grafana/provisioning/dashboards_repo",
                    "foldersFromFilesStructure": True,
                },
            },
        ],
    }

    dashboards_dict_yaml = yaml.dump(dashboards_dict)

    dashboards_yaml_path = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "dashboards",
        "dashboards.yaml",
    ).expanduser()

    dashboards_yaml_path.parent.mkdir(parents=True, exist_ok=True)

    with open(dashboards_yaml_path, "w") as fw:
        fw.write(dashboards_dict_yaml)

    ret = {
        "dashboards_repo": dashboards_repo,
        "dashboards_yaml_path": dashboards_yaml_path,
    }

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.md(
                f"```json\n{json.dumps(ret, indent=2, default=str)}\n```"
            ),
            "dashboards_repo": MetadataValue.path(dashboards_repo),
            "dashboards_yaml_path": MetadataValue.path(dashboards_yaml_path),
            "dashboards_dict_yaml": MetadataValue.md(
                f"```yaml\n{dashboards_dict_yaml}\n```"
            ),
            "dashboards": MetadataValue.md(
                f"```json\n{json.dumps(dashboards, indent=2, default=str)}\n```"
            ),
        },
    )


# @asset(
#     **ASSET_HEADER,
#     ins={
#         "CONFIG": AssetIn(
#             AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
#         ),
#     },
#     description=textwrap.dedent(
#         """
#         """
#     )
# )
# def dashboard_minifarm(
#         context: AssetExecutionContext,
#         CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
# ) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
#     env: Dict = CONFIG.env
#
#     # config_engine: ConfigEngine = CONFIG.config_engine
#
#     service_name_loki = "loki"
#     # container_name_loki, host_name_loki = get_docker_compose_names(
#     #     context=context,
#     #     service_name=service_name_loki,
#     #     landscape_id=env.get("LANDSCAPE", "default"),
#     #     domain_lan=config_engine.openstudiolandscapes__domain_lan,
#     # )
#
#     datasources_loki_dict = {
#         "apiVersion": 1,
#         "datasources": [
#             {
#                 "name": "Loki",
#                 "type": "loki",
#                 "access": "proxy",
#                 "orgId": 1,
#                 "url": f"http://{service_name_loki}:{CONFIG.grafana_loki_port_container}",
#                 "basicAuth": False,
#                 "isDefault": True,
#                 "version": 1,
#                 "editable": False,
#                 "jsonData": {
#                     "timeout": 60,
#                     "maxLines": 1000,
#                 },
#             },
#         ],
#     }
#
#     datasources_loki_dict_yaml = yaml.dump(datasources_loki_dict)
#
#     loki_yaml_path = pathlib.Path(
#         env["DOT_LANDSCAPES"],
#         env.get("LANDSCAPE", "default"),
#         f"{dist.name}",
#         "datasources",
#         "loki.yaml",
#     ).expanduser()
#
#     loki_yaml_path.parent.mkdir(parents=True, exist_ok=True)
#
#     with open(loki_yaml_path, "w") as fw:
#         fw.write(datasources_loki_dict_yaml)
#
#     yield Output(loki_yaml_path)
#
#     yield AssetMaterialization(
#         asset_key=context.asset_key,
#         metadata={
#             "__".join(context.asset_key.path): MetadataValue.path(loki_yaml_path),
#             "datasources_loki_dict_yaml": MetadataValue.md(f"```yaml\n{datasources_loki_dict_yaml}\n```"),
#         },
#     )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
)
def compose_networks(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[
    Output[Dict[str, Dict[str, Dict[str, str]]]] | AssetMaterialization, None, None
]:
    env: Dict = CONFIG.env

    compose_network_mode = DockerComposePolicies.NETWORK_MODE.BRIDGE

    docker_dict = get_network_dicts(
        context=context,
        compose_network_mode=compose_network_mode,
        env=env,
    )

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "compose_network_mode": MetadataValue.text(compose_network_mode.value),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "compose_networks": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
        "grafana_ini": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "grafana_ini"]),
        ),
        "data_sources_grafana": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "data_sources_grafana"]),
        ),
        "dashboards_grafana": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "dashboards_grafana"]),
        ),
    },
)
def compose_grafana(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    compose_networks: Dict,  # pylint: disable=redefined-outer-name
    grafana_ini: pathlib.Path,  # pylint: disable=redefined-outer-name
    data_sources_grafana: pathlib.Path,  # pylint: disable=redefined-outer-name
    dashboards_grafana: Dict[str, pathlib.Path],  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks:
        network_dict = {"networks": list(compose_networks.get("networks", {}).keys())}
        ports_dict = {
            "ports": [
                f"{CONFIG.grafana_port_host}:{CONFIG.grafana_port_container}",
            ]
        }
    elif "network_mode" in compose_networks:
        network_dict = {"network_mode": compose_networks["network_mode"]}

    var_lib = CONFIG.GF_PATHS_DATA_expanded

    old_umask = os.umask(0o000)

    var_lib.mkdir(
        parents=True,
        exist_ok=True,
        mode=0o777,
    )

    os.umask(old_umask)

    volumes_dict = {
        "volumes": [
            f"{var_lib.as_posix()}:/var/lib/grafana:rw",
            f"{grafana_ini.as_posix()}:/etc/grafana/grafana.ini:ro",
            f"{data_sources_grafana.as_posix()}:/etc/grafana/provisioning/datasources/{data_sources_grafana.name}:ro",
            f"{dashboards_grafana['dashboards_yaml_path'].as_posix()}:/etc/grafana/provisioning/dashboards/{dashboards_grafana['dashboards_yaml_path'].name}:ro",
            f"{dashboards_grafana['dashboards_repo'].as_posix()}:/etc/grafana/provisioning/{dashboards_grafana['dashboards_repo'].name}:ro",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:
        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": list(
            {
                *_volume_relative,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name = "grafana"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )

    # Todo
    #  - [ ] https://github.com/michimussato/OpenStudioLandscapes/issues/63
    # service: DockerComposeServiceDefinition = {
    #     "container_name": container_name,
    #     # "hostname": host_name,
    #     "domainname": config_engine.openstudiolandscapes__domain_lan,
    #     "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS,
    #     "image": f"{CONFIG.grafana_image}:{CONFIG.grafana_image_version}",
    #
    #     "depends_on": {
    #         "prometheus": {
    #             "condition": DockerComposePolicies.DEPENDENCY_ON_POLICY.SERVICE_STARTED,
    #         },
    #         "loki": {
    #             "condition": DockerComposePolicies.DEPENDENCY_ON_POLICY.SERVICE_STARTED,
    #         },
    #     },
    #     **copy.deepcopy(network_dict),
    #     **copy.deepcopy(ports_dict),
    #     **copy.deepcopy(volumes_dict),
    # }

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                # "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                "image": f"{CONFIG.grafana_image}:{CONFIG.grafana_image_version}",
                "depends_on": {
                    "prometheus": {
                        "condition": "service_started",
                    },
                    "loki": {
                        "condition": "service_started",
                    },
                },
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                **copy.deepcopy(network_dict),
                **copy.deepcopy(ports_dict),
                **copy.deepcopy(volumes_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "compose_networks": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
        # "mimir_yaml": AssetIn(
        #     AssetKey([*ASSET_HEADER["key_prefix"], "mimir_yaml"]),
        # ),
        "prometheus_yaml": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "prometheus_yaml"]),
        ),
    },
    description=textwrap.dedent("""
        Prometheus with Alloy (which replaces deprectated Promtail),
        needs to be launched with `--web.enable-remote-write-receiver`.
        
        The reason for this is with Promtail, Prometheus scraped (pull)
        the metrics. In contrast, with Alloy, Prometheus receives (push)
        the metrics from Alloy.
        """),
)
def compose_prometheus(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    compose_networks: Dict,  # pylint: disable=redefined-outer-name
    # mimir_yaml: pathlib.Path,  # pylint: disable=redefined-outer-name
    prometheus_yaml: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
    """ """

    # Todo:
    #  - [ ] https://prometheus.io/docs/guides/basic-auth/

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks:
        network_dict = {"networks": list(compose_networks.get("networks", {}).keys())}
        ports_dict = {
            "ports": [
                f"{CONFIG.prometheus_port_host}:{CONFIG.prometheus_port_container}",
            ]
        }
    elif "network_mode" in compose_networks:
        network_dict = {"network_mode": compose_networks["network_mode"]}

    volumes_dict = {
        "volumes": [
            # f"{mimir_yaml.as_posix()}:/etc/mimir/config.yaml:rw",
            # f"{CONFIG.prometheus_data_expanded.as_posix()}:/prometheus/data:rw",
            f"{prometheus_yaml.as_posix()}:/etc/prometheus/prometheus.yaml:ro",
            # f"{grafana_ini.as_posix()}:/etc/grafana/grafana.ini:ro",
            # f"{data_sources_loki.as_posix()}:/etc/grafana/provisioning/datasources/loki.yaml:ro",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:
        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": [
            *_volume_relative,
            *CONFIG.local_bind_volumes,
        ]
    }

    service_name = "prometheus"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                # "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                "image": CONFIG.prometheus_image,
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                "command": [
                    # "--config.file=/etc/mimir/config.yaml",
                    "--web.enable-remote-write-receiver",
                    # https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
                    # "--storage.tsdb.path=/prometheus/data",
                    # "--storage.tsdb.retention.time=1w",
                    # "--storage.tsdb.retention.size=5GB",
                    "--config.file=/etc/prometheus/prometheus.yaml",
                ],
                **copy.deepcopy(network_dict),
                **copy.deepcopy(ports_dict),
                **copy.deepcopy(volumes_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


# @asset(
#     **ASSET_HEADER,
#     ins={
#         "CONFIG": AssetIn(
#             AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
#         ),
#         "compose_networks": AssetIn(
#             AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
#         ),
#         "mimir_yaml": AssetIn(
#             AssetKey([*ASSET_HEADER["key_prefix"], "mimir_yaml"]),
#         ),
#     },
# )
# def compose_mimir(
#         context: AssetExecutionContext,
#         CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
#         compose_networks: Dict,  # pylint: disable=redefined-outer-name
#         mimir_yaml: pathlib.Path,  # pylint: disable=redefined-outer-name
# ) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
#     """ """
#
#     env: Dict = CONFIG.env
#
#     config_engine: ConfigEngine = CONFIG.config_engine
#
#     network_dict = {}
#     ports_dict = {}
#
#     if "networks" in compose_networks:
#         network_dict = {"networks": list(compose_networks.get("networks", {}).keys())}
#         ports_dict = {
#             "ports": [
#                 f"{CONFIG.grafana_mimir_port_host}:{CONFIG.grafana_mimir_port_container}",
#             ]
#         }
#     elif "network_mode" in compose_networks:
#         network_dict = {"network_mode": compose_networks["network_mode"]}
#
#     # var_lib = pathlib.Path(
#     #     env["DOT_LANDSCAPES"],
#     #     env.get("LANDSCAPE", "default"),
#     #     f"{dist.name}",
#     #     "var",
#     #     "lib",
#     #     "grafana",
#     # ).expanduser()
#
#     # old_umask = os.umask(0o000)
#
#     # var_lib.mkdir(
#     #     parents=True,
#     #     exist_ok=True,
#     #     mode=0o777,
#     # )
#
#     # os.umask(old_umask)
#
#     volumes_dict = {
#         "volumes": [
#             f"{mimir_yaml.as_posix()}:/etc/mimir/config.yaml:rw",
#             # f"{grafana_ini.as_posix()}:/etc/grafana/grafana.ini:ro",
#             # f"{data_sources_loki.as_posix()}:/etc/grafana/provisioning/datasources/loki.yaml:ro",
#         ]
#     }
#
#     # For portability, convert absolute volume paths to relative paths
#
#     _volume_relative = []
#
#     for v in volumes_dict["volumes"]:
#         host, container = v.split(":", maxsplit=1)
#
#         volume_dir_host_rel_path = get_relative_path_via_common_root(
#             context=context,
#             path_src=CONFIG.docker_compose_expanded,
#             path_dst=pathlib.Path(host),
#             path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
#         )
#
#         _volume_relative.append(
#             f"{volume_dir_host_rel_path.as_posix()}:{container}",
#         )
#
#     volumes_dict = {
#         "volumes": [
#             *_volume_relative,
#         ]
#     }
#
#     service_name = "mimir"
#     container_name, host_name = get_docker_compose_names(
#         context=context,
#         service_name=service_name,
#         landscape_id=env.get("LANDSCAPE", "default"),
#         domain_lan=config_engine.openstudiolandscapes__domain_lan,
#     )
#
#     docker_dict = {
#         "services": {
#             service_name: {
#                 "container_name": container_name,
#                 # "hostname": host_name,
#                 "domainname": config_engine.openstudiolandscapes__domain_lan,
#                 "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
#                 "image": CONFIG.grafana_mimir_image,
#                 "command": [
#                     "--config.file=/etc/mimir/config.yaml",
#                 ],
#                 **copy.deepcopy(network_dict),
#                 **copy.deepcopy(ports_dict),
#                 **copy.deepcopy(volumes_dict),
#             },
#         },
#     }
#
#     docker_yaml = yaml.dump(docker_dict)
#
#     yield Output(docker_dict)
#
#     yield AssetMaterialization(
#         asset_key=context.asset_key,
#         metadata={
#             "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
#         },
#     )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "compose_networks": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
        "loki_yaml": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "loki_yaml"]),
        ),
    },
)
def compose_loki(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    compose_networks: Dict,  # pylint: disable=redefined-outer-name
    loki_yaml: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    # network_dict = {}
    # ports_dict = {}
    #
    # if "networks" in compose_networks:
    #     network_dict = {"networks": list(compose_networks.get("networks", {}).keys())}
    #     ports_dict = {
    #         "ports": [
    #             f"{CONFIG.grafana_port_host}:{CONFIG.grafana_port_container}",
    #         ]
    #     }
    # elif "network_mode" in compose_networks:
    #     network_dict = {"network_mode": compose_networks["network_mode"]}

    # var_lib = pathlib.Path(
    #     env["DOT_LANDSCAPES"],
    #     env.get("LANDSCAPE", "default"),
    #     f"{dist.name}",
    #     "var",
    #     "lib",
    #     "grafana",
    # ).expanduser()

    # old_umask = os.umask(0o000)

    # var_lib.mkdir(
    #     parents=True,
    #     exist_ok=True,
    #     mode=0o777,
    # )

    # os.umask(old_umask)

    # volumes_dict = {
    #     "volumes": [
    #         f"{var_lib.as_posix()}:/var/lib/grafana:rw",
    #         f"{grafana_ini.as_posix()}:/etc/grafana/grafana.ini:ro",
    #         f"{data_sources_loki.as_posix()}:/etc/grafana/provisioning/datasources/loki.yaml:ro",
    #     ]
    # }

    # For portability, convert absolute volume paths to relative paths

    # _volume_relative = []
    #
    # for v in volumes_dict["volumes"]:
    #     host, container = v.split(":", maxsplit=1)
    #
    #     volume_dir_host_rel_path = get_relative_path_via_common_root(
    #         context=context,
    #         path_src=CONFIG.docker_compose_expanded,
    #         path_dst=pathlib.Path(host),
    #         path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
    #     )
    #
    #     _volume_relative.append(
    #         f"{volume_dir_host_rel_path.as_posix()}:{container}",
    #     )

    # volumes_dict = {
    #     "volumes": [
    #         *_volume_relative,
    #     ]
    # }

    if "networks" in compose_networks:
        network_dict_loki = {
            "networks": list(compose_networks.get("networks", {}).keys())
        }
        ports_dict_loki = {
            "ports": [
                f"{CONFIG.grafana_loki_port_host}:{CONFIG.grafana_loki_port_container}",
            ]
        }
    elif "network_mode" in compose_networks:
        network_dict_loki = {"network_mode": compose_networks["network_mode"]}

    volumes_dict_loki = {
        "volumes": [
            f"{loki_yaml.as_posix()}:/etc/loki/local-config.yaml:ro",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative_loki = []

    for v in volumes_dict_loki["volumes"]:
        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative_loki.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict_loki = {
        "volumes": list(
            {
                *_volume_relative_loki,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name_loki = "loki"
    container_name_loki, host_name_loki = get_docker_compose_names(
        context=context,
        service_name=service_name_loki,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )

    docker_dict = {
        "services": {
            service_name_loki: {
                "container_name": container_name_loki,
                # "hostname": host_name_loki,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                "image": CONFIG.grafana_loki_image,
                "command": ["-config.file=/etc/loki/local-config.yaml"],
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                **copy.deepcopy(network_dict_loki),
                **copy.deepcopy(ports_dict_loki),
                **copy.deepcopy(volumes_dict_loki),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "compose_grafana": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_grafana"]),
        ),
        "compose_prometheus": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_prometheus"]),
        ),
        # "compose_mimir": AssetIn(
        #     AssetKey([*ASSET_HEADER["key_prefix"], "compose_mimir"]),
        # ),
        "compose_loki": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_loki"]),
        ),
    },
)
def compose_maps(
    context: AssetExecutionContext,
    **kwargs,  # pylint: disable=redefined-outer-name
) -> Generator[Output[List[Dict]] | AssetMaterialization, None, None]:
    ret = list(kwargs.values())

    context.log.info(ret)

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
        },
    )
